# Generated by Django 3.2.5 on 2021-07-21 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 9, 28, 50, 200216)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_post',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 9, 28, 50, 200216)),
        ),
    ]
