# Generated by Django 3.2.5 on 2021-07-23 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210721_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 21, 3, 11, 916601)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_post',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 21, 3, 11, 916601)),
        ),
    ]
