# Generated by Django 3.2.5 on 2021-07-23 17:16

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210723_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 21, 46, 13, 909367)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mycomment',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_post',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 21, 46, 13, 909367)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
